version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo:17.0
    labels:
      - "maintainer=aashish.thapa@smarten.com.np"
    container_name: web-odoo
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./local-addons:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise
      # - ./upgrade-scripts:/mnt/upgrade-scripts
    environment:
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo
    restart: always
    # entrypoint: /mnt/upgrade-scripts/entrypoint.sh
  db:
    image: postgres:16.1-alpine3.19
    container_name: db-odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo
    restart: always
  pgadmin:
    container_name: pgadmin-odoo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: amdin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5434:80
    networks:
      - odoo
    restart: always
  proxy:
    depends_on:
            - web
    container_name: odoo_proxy
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
        - "8069:8069"
        - "80:80"
    networks:
      - odoo
    restart: always

networks:
  odoo:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin:
  # upgrade-scripts:
